# -*- coding: utf-8 -*-
"""Name_Entity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T86zfGWULQQGzyFkPFbTk9dfU7fcp6gt
"""

pip install transformers torch

from transformers import pipeline

# Load pre-trained NER model
ner_pipeline = pipeline(
    "ner",
    model="dbmdz/bert-large-cased-finetuned-conll03-english",
    aggregation_strategy="simple"
)

def extract_entities(text):
    entities = ner_pipeline(text)
    return entities
# Take input from user
user_text = input("Enter text for Named Entity Recognition:\n")
results = extract_entities(user_text)

print("\n=== Named Entities ===")
for ent in results:
    print(f"Entity: {ent['word']}, Type: {ent['entity_group']}")

