# -*- coding: utf-8 -*-
"""Question_Answering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_pDBF640G1XcqXeKEjt_myQocTjZRCH
"""

pip install transformers torch

# Install required libraries
# pip install transformers torch

from transformers import pipeline

# Load pre-trained Question Answering model
qa_model = pipeline(
    "question-answering",
    model="distilbert-base-cased-distilled-squad"
)

# Take context from user
context = input("\nEnter the context paragraph:\n")

# Take question from user
question = input("\nEnter your question:\n")

# Get answer
result = qa_model(
    question=question,
    context=context
)

# Print answer
print("\nAnswer:", result["answer"])

