# -*- coding: utf-8 -*-
"""summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFF-PlS3qpg3aoxa7_DBveeBxJT83ab_
"""

pip install transformers torch

from transformers import pipeline

# Load pre-trained summarization model
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

def summarize_text(user_text):
    summary = summarizer(
        user_text,
        max_length=120,
        min_length=40,
        do_sample=False
    )
    return summary[0]["summary_text"]

# -----------------------------
# Take input from the user
# -----------------------------
print("Enter the text to summarize :")

lines = []
while True:
    line = input()
    if line.strip() == "":
        break
    lines.append(line)

user_input_text = " ".join(lines)

# Generate summary
result = summarize_text(user_input_text)

print("\n=== Summary ===")
print(result)

