# -*- coding: utf-8 -*-
"""Text_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OqLmymJE7ILURQSH0HnjoT6FpWG9CUb
"""

pip install transformers datasets torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Load pretrained sentiment model
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Take input from user
text = input("Enter your review: ")

# Tokenize input
inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

# Model prediction
with torch.no_grad():
    outputs = model(**inputs)

# Get predicted label
prediction = torch.argmax(outputs.logits, dim=1).item()
label = model.config.id2label[prediction]

# Print result
print("\nReview Analysis:")
print(f"Text      : {text}")
print(f"Sentiment : {label}")

